# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gimme}
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Justin Searls}]
  s.date = %q{2012-02-25}
  s.description = %q{gimme attempts to bring to Ruby a test double workflow akin to Mockito in Java. Major distinctions include preserving arrange-act-assert in tests, fast feedback for methods the double's real counterpart may not know how to respond to, no string/symbolic representations of methods, argument captors, and strong opinions (weakly held). }
  s.email = %q{searls@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.markdown",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/argument_captors.feature",
    "features/gimme_next.feature",
    "features/step_definitions/gimme_steps.rb",
    "features/stub_basic.feature",
    "features/stub_matchers.feature",
    "features/stub_sensible_defaults.feature",
    "features/support/animals.rb",
    "features/support/env.rb",
    "features/unknown_methods.feature",
    "features/verify_matcher_anything.feature",
    "features/verify_no_args.feature",
    "features/verify_with_args.feature",
    "gimme.gemspec",
    "lib/gimme-double.rb",
    "lib/gimme.rb",
    "lib/gimme/captor.rb",
    "lib/gimme/errors.rb",
    "lib/gimme/gives.rb",
    "lib/gimme/matchers.rb",
    "lib/gimme/method_resolver.rb",
    "lib/gimme/rspec_adapter.rb",
    "lib/gimme/test_double.rb",
    "lib/gimme/verifies.rb",
    "spec/gimme/captor_spec.rb",
    "spec/gimme/errors_spec.rb",
    "spec/gimme/gives_spec.rb",
    "spec/gimme/matchers_spec.rb",
    "spec/gimme/test_double_spec.rb",
    "spec/gimme/verifies_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/searls/gimme}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{gimme — a low-specification test double library for Ruby}
  s.test_files = [
    "spec/gimme/captor_spec.rb",
    "spec/gimme/errors_spec.rb",
    "spec/gimme/gives_spec.rb",
    "spec/gimme/matchers_spec.rb",
    "spec/gimme/test_double_spec.rb",
    "spec/gimme/verifies_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rspec-given>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<guard-cucumber>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<growl_notify>, [">= 0"])
      s.add_development_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.1"])
      s.add_development_dependency(%q<cucumber>, [">= 0.10.0"])
    else
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rspec-given>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<guard-cucumber>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<growl_notify>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.3.1"])
      s.add_dependency(%q<cucumber>, [">= 0.10.0"])
    end
  else
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rspec-given>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<guard-cucumber>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<growl_notify>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.3.1"])
    s.add_dependency(%q<cucumber>, [">= 0.10.0"])
  end
end

